### ISSUE TITLE
jni .so file doesn't work

### ISSUE THREAD

**Issue by zzang9083** [mzsanford/cld#32]
I'm trying to build the Java port of cld on centos 64-bit , using Virtualbox.
I followed your 'README.md' and Setting was finished.
i made new java project and i move 'cld/ports/java/java/src' to new '/src'.
but it doesn't work. 
error is

`Exception in thread "main" java.lang.UnsatisfiedLinkError:  com.mzsanford.cld.CompactLanguageDetector.detectLanguageDetails(Ljava/lang/String;ZZZZLjava/lang/String;)Lcom/mzsanford/cld/LanguageDetectionResult;
    at com.mzsanford.cld.CompactLanguageDetector.detectLanguageDetails(Native Method)
    at com.mzsanford.cld.CompactLanguageDetector.detect(CompactLanguageDetector.java:23)
    at com.mzsanford.cld.CompactLanguageDetector.main(CompactLanguageDetector.java:41) `

what should i do?

**Comment by josephxsxn** [comment]
Saddly I am having the same issue.. It does not appear to matter what way I try I cannot get past this with a modern Operating System (Ubuntu 17) and newer Java OpenJDK8... Java 8 appears to have changed the location of the jni header files so you have to symlink them into the includes folder to even get the Java Pom to compile...

**Comment by mzsanford** [comment]
I have two Dockerfiles in the tests directory that build the Java port for OpenJDK and the Oracle JDK respectively. Try out `docker build -t test/cld:centos6-openjdk -f tests/Dockerfile.centos6.openjdk .` and let me know if that works for you … `tests/Dockerfile.centos6.openjdk` may contain whatever is missing from the build steps. Let me know what CentOS version and I can create another Dockerfile to try and replicate the error.
